const authRoutes = require('@routes/authRoutes');
const locationRoutes = require('@routes/locationRoutes');
const resourceRoutes = require('@routes/resourceRoutes');
const categoryRoutes = require('@routes/categoryRoutes');
const staffRoutes = require('@routes/staffRoutes');
const serviceRoutes = require('@routes/ServicesRoutes');
const serviceGroupRoutes = require('@routes/servicesGroupRoutes');
const priceTierRoutes = require('@routes/PriceTierRoutes');
const bookingRoutes = require('@routes/bookingRoutes');
const waitlistRoutes = require('@routes/waitlistRoutes');
const calendarSettingsRoutes = require('@routes/calendarSettingsRoutes');
const productRoutes = require('@routes/productRoutes');
const supplierRoutes = require('@routes/supplierRoutes');
const stockOrderRoutes = require('@routes/stockOrderRoutes');
const promoCodeRoutes = require('@routes/PromoCodeRoutes');
const discountsRoutes = require('@routes/DiscountRoutes');
const packagesRoutes = require('@routes/PackagesRoutes');
const notificationRoutes = require('@routes/notificationRoutes');

module.exports = (app) => {
  app.use('/auth', authRoutes);
  app.use('/location', locationRoutes);
  app.use('/resource', resourceRoutes);
  app.use('/category', categoryRoutes);
  app.use('/staff', staffRoutes);
  app.use('/services', serviceRoutes);
  app.use('/service-groups', serviceGroupRoutes);
  app.use('/price-tiers', priceTierRoutes);
  app.use('/booking', bookingRoutes);
  app.use('/waitlist', waitlistRoutes);
  app.use('/calendar-settings', calendarSettingsRoutes);
  app.use('/products', productRoutes);
  app.use('/suppliers', supplierRoutes);
  app.use('/stock-orders', stockOrderRoutes);
  app.use('/promo-codes', promoCodeRoutes);
  app.use('/discounts', discountsRoutes);
  app.use('/packages', packagesRoutes);
  app.use('/gift-vouchers', require('@routes/GiftVoucherRoutes'));
  app.use('/notifications', notificationRoutes);
};
